server:
  port: 9100
spring:
  application:
    name: gateway-test
  cloud:
    config:
      discovery:
        service-id: config-test
        enabled: true
      profile: test
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        enabled: true
        health-check-path: ${management.context-path}/health
zuul:
  routes:
    myupms:
      path: /myupms/**
      serviceId: upms
   myauth:
      path: /myauth/**
      serviceId: auth

