server:
  port: 9200
spring:
  application:
    name: upms
  cloud:
    config:
      discovery:
        service-id: config
        enabled: true
      profile: dev
      fail-fast: true
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ws_spring_cloud_demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000 # 客户端等待连接池连接的最大毫秒数
      minimum-idle: 8 # 连接池中维护的最小空闲连接数
      maximum-pool-size: 12 #配置最大池大小
      idle-timeout: 300000 # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000 # 池中连接关闭后的最长生命周期（以毫秒为单位）
      auto-commit: true # 配置从池返回的连接的默认自动提交行为
      pool-name: DatebookHikariCP
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
